import os
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = ['hello.c', 'mailbox_sample.c', 'msgq_sample.c', 'mutex_sample.c', 'semaphore_sample.c', 'thread_sample.c']

group = DefineGroup("app", src, depend = [''], CPPPATH=CPPPATH)
Return('group')
